version: 2

sources:
  - name: raw_adventureworks
    database: FEA24_9
    schema: raw_adventure_works
    tables:
      - name: salesorderdetail
        columns:
          - name: salesorderdetailid
            tests:
              - unique
              - not_null
            
      - name: salesorderheader
        columns:
          - name: salesorderid
            tests:
              - unique
              - not_null
      
      - name: address
        columns:
          - name: addressid
            tests:
              - unique
              - not_null
      
      - name: countryregion
        columns:
          - name: countryregioncode
            tests:
              - unique
              - not_null

      - name: stateprovince
        columns:
          - name: stateprovinceid
            tests:
              - unique
              - not_null

      - name: creditcard
        columns:
          - name: creditcardid
            tests:
              - unique
              - not_null

      - name: salesreason
        columns:
          - name: salesreasonid
            tests:
                - unique
                - not_null

      - name: salesorderheadersalesreason
      
      - name: product
        columns:
          - name: productid
            tests:
              - unique
              - not_null

      - name: productcategory
        columns:
          - name: productcategoryid
            tests:
              - unique
              - not_null

      - name: customer
        columns:
          - name: customerid
            tests:
              - unique
              - not_null

      - name: person
        columns:
          - name: businessentityid
            tests:
              - unique
              - not_null

      - name: store
        columns:
          - name: businessentityid
            tests:
              - unique
              - not_null

                  
                  
                  